/**
 * Tutor "Student Activity Points Report" PDF export.
 *
 * This mirrors the report generated by the React Native tutor app
 * (src/screens/TutorStudentsScreen.tsx -> buildPdfHtml + react-native-html-to-pdf)
 * as closely as possible: same header, same title band, same ledger table
 * layout/colors/typography, same PASS/PENDING trophy badges, same footer.
 *
 * Since the browser can't hand HTML off to a native WebKit PDF renderer the
 * way react-native-html-to-pdf does, we render the exact same markup/CSS to
 * an off-screen DOM node, rasterize each page with html2canvas, and paste
 * the images into a jsPDF document.
 *
 * Pagination note
 * ----------------
 * A student can legitimately have dozens of approved activities (one row
 * each). Earlier versions of this file treated a whole student "block" as an
 * atomic unit that always had to land on a single page — if that block was
 * taller than a printable A4 page, the rasterized image simply ran off the
 * bottom edge of the page and everything past that point was silently lost.
 * That's why long activity lists used to get cut off mid-list with no
 * warning.
 *
 * This version paginates at the *row* level instead. A student's name/reg/
 * total header is measured and placed first; their activity rows are then
 * packed onto the page one at a time. If the list runs past the bottom of a
 * page, it simply continues onto the next page under a small "(continued)"
 * marker — nothing is ever dropped, and every activity always appears
 * exactly once, in full.
 */

import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { calcCappedPoints, passThreshold } from './calcPoints';

// ---------------------------------------------------------------------
// Layout constants
// ---------------------------------------------------------------------
// Rendered at this pixel width off-screen, then scaled down to fit the
// printable width of an A4 jsPDF page (210mm - margins).
const RENDER_WIDTH_PX = 900;

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;
const MARGIN_X_MM = 10;
const MARGIN_TOP_MM = 10;
const FOOTER_RESERVE_MM = 12;

const CONTENT_WIDTH_MM = A4_WIDTH_MM - MARGIN_X_MM * 2;
// px-per-mm at the scale we render/rasterize at, used to convert the real
// printable page height into a px budget for the packing algorithm below.
const PX_PER_MM = RENDER_WIDTH_PX / CONTENT_WIDTH_MM;
// Max height (px, at RENDER_WIDTH_PX) of content allowed on one page before
// a new page is started. Derived from the actual A4 printable area (rather
// than a hand-picked magic number) so the budget always matches what will
// really fit, with a small safety margin.
const PAGE_CONTENT_MAX_PX = Math.floor(
  (A4_HEIGHT_MM - MARGIN_TOP_MM - FOOTER_RESERVE_MM) * PX_PER_MM * 0.97
);

function getBatchName(b) {
  return typeof b === 'object' ? b?.name ?? '' : b ?? '';
}
function getBranchName(b) {
  return typeof b === 'object' ? b?.name ?? '' : b ?? '';
}

// ---------------------------------------------------------------------
// Shared CSS — a near-verbatim port of the RN report's stylesheet, with a
// larger crest and a few professional-polish tweaks (zebra striping on
// long activity lists, a card-style shadow around the ledger, a clearer
// "continued" marker for split activity lists).
// ---------------------------------------------------------------------
const REPORT_CSS = `
.mti-pdf-doc, .mti-pdf-doc * { margin: 0; padding: 0; box-sizing: border-box; }
.mti-pdf-doc {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  color: #1e293b;
  background: #ffffff;
  font-size: 13px;
  width: ${RENDER_WIDTH_PX}px;
  padding: 18px 22px 10px 22px;
}
.mti-pdf-doc .header {
  display: table;
  width: 100%;
  padding-bottom: 16px;
  border-bottom: 3px solid #0f2864;
  margin-bottom: 12px;
}
.mti-pdf-doc .header-logo-cell { display: table-cell; vertical-align: middle; width: 150px; }
.mti-pdf-doc .header-logo-cell img { width: 128px; height: auto; display: block; }
.mti-pdf-doc .header-text { display: table-cell; vertical-align: middle; text-align: center; }
.mti-pdf-doc .header-spacer-cell { display: table-cell; width: 150px; }
.mti-pdf-doc .dept-name { font-size: 18px; font-weight: 800; color: #0f2864; letter-spacing: 0.6px; margin-bottom: 4px; }
.mti-pdf-doc .inst-name { font-size: 15px; font-weight: 700; color: #1e293b; margin-bottom: 3px; }
.mti-pdf-doc .inst-sub { font-size: 10px; color: #64748b; margin-top: 1px; font-weight: 500; }
.mti-pdf-doc .title-band {
  background: linear-gradient(135deg, #0f2864 0%, #1e40af 100%);
  color: #ffffff;
  text-align: center;
  padding: 11px 14px;
  font-size: 14px;
  font-weight: 800;
  border-radius: 5px;
  margin: 14px 0 18px 0;
  letter-spacing: 1px;
  box-shadow: 0 2px 6px rgba(15, 40, 100, 0.25);
}
.mti-pdf-doc .ledger-wrap {
  border-radius: 6px;
  overflow: hidden;
  box-shadow: 0 1px 4px rgba(15, 23, 42, 0.12);
}
.mti-pdf-doc .ledger-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
  background: #ffffff;
}
.mti-pdf-doc .ledger-table thead tr th {
  background-color: #0f2864;
  color: #ffffff;
  font-weight: 700;
  text-transform: uppercase;
  font-size: 10px;
  letter-spacing: 0.6px;
  padding: 10px 12px;
  border: 1px solid #0a1f54;
}
.mti-pdf-doc .student-profile-row td {
  border: 1.5px solid #94a3b8;
  background-color: #f0f4ff;
}
.mti-pdf-doc .student-profile-row.continuation td {
  background-color: #e8edfb;
}
.mti-pdf-doc .sl-cell {
  text-align: center;
  font-weight: 800;
  font-size: 14px;
  color: #0f2864;
  background-color: #dce7ff !important;
  width: 42px;
  border-right: 2px solid #0f2864 !important;
}
.mti-pdf-doc .sl-cell.muted { color: #6b83b8; }
.mti-pdf-doc .student-name-meta { padding: 10px 14px; }
.mti-pdf-doc .name-text {
  font-size: 14px;
  font-weight: 800;
  color: #0f2864;
  text-transform: uppercase;
  letter-spacing: 0.3px;
  margin-bottom: 4px;
}
.mti-pdf-doc .continued-tag {
  font-size: 10px;
  font-weight: 700;
  color: #64748b;
  text-transform: none;
  letter-spacing: 0.2px;
  margin-left: 6px;
}
.mti-pdf-doc .reg-meta-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.mti-pdf-doc .reg-text { font-size: 10px; color: #475569; }
.mti-pdf-doc .lat-label {
  background: #fef3c7;
  color: #92400e;
  font-size: 9px;
  font-weight: 700;
  padding: 1px 5px;
  border-radius: 3px;
  border: 1px solid #f59e0b;
}
.mti-pdf-doc .cert-count-badge {
  background: #e0f2fe;
  color: #0369a1;
  font-size: 9px;
  font-weight: 700;
  padding: 1px 6px;
  border-radius: 3px;
  border: 1px solid #7dd3fc;
}
.mti-pdf-doc .pt-blank { background-color: #f0f4ff !important; }
.mti-pdf-doc .continuation-note-cell {
  text-align: center;
  vertical-align: middle;
  background: #e8edfb !important;
  border: 1.5px solid #94a3b8 !important;
  color: #64748b;
  font-size: 9px;
  font-weight: 700;
  letter-spacing: 0.3px;
  padding: 4px;
}
.mti-pdf-doc .cert-item-row td {
  border: 1px solid #e2e8f0;
  padding: 6px 12px;
  background: #ffffff;
}
.mti-pdf-doc .cert-item-row.alt td { background: #f8fafc; }
.mti-pdf-doc .cert-name-cell { color: #334155; font-size: 11px; font-weight: 500; padding-left: 20px !important; }
.mti-pdf-doc .cert-index { color: #94a3b8; font-size: 10px; margin-right: 4px; font-weight: 600; }
.mti-pdf-doc .cert-pts { color: #0f2864; font-weight: 700 !important; text-align: center; }
.mti-pdf-doc .empty-certs-text { color: #94a3b8; font-style: italic; }
.mti-pdf-doc .points-cell { text-align: center; font-weight: 600; color: #475569; width: 66px; }
.mti-pdf-doc .total-score-cell {
  text-align: center;
  background: #0f2864 !important;
  border: 2px solid #0a1f54 !important;
  width: 76px;
  padding: 6px 4px;
}
.mti-pdf-doc .total-score-num { font-size: 24px; font-weight: 900; color: #ffffff; line-height: 1.1; }
.mti-pdf-doc .total-score-label { font-size: 9px; font-weight: 600; color: #93c5fd; text-transform: uppercase; letter-spacing: 0.5px; }
.mti-pdf-doc .status-trophy-cell {
  text-align: center;
  background: #ffffff !important;
  border: 1.5px solid #94a3b8 !important;
  width: 70px;
  padding: 4px;
}
.mti-pdf-doc .trophy-wrapper { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 2px; }
.mti-pdf-doc .trophy-wrapper svg { width: 24px; height: 24px; }
.mti-pdf-doc .pass-label { font-size: 9px; font-weight: 800; color: #15803d; letter-spacing: 0.5px; }
.mti-pdf-doc .fail-wrapper { display: flex; align-items: center; justify-content: center; height: 100%; }
.mti-pdf-doc .fail-label { font-size: 9px; font-weight: 700; color: #94a3b8; letter-spacing: 0.5px; }
.mti-pdf-doc .spacer-row td {
  height: 14px;
  background: transparent !important;
  border: none !important;
  padding: 0 !important;
}
.mti-pdf-doc .divider { border: none; border-top: 2px solid #e2e8f0; margin: 20px 0 8px 0; }
.mti-pdf-doc .report-meta-footer { font-size: 10px; color: #64748b; font-weight: 500; }
.mti-pdf-doc .footer-row { display: flex; justify-content: space-between; align-items: center; }
`;

// Inline trophy SVG (stand-in for the Material Icons "emoji_events" glyph
// used in the RN app — avoids depending on a webfont being loaded in time
// for html2canvas to rasterize it).
const TROPHY_SVG = `<svg viewBox="0 0 24 24" fill="#d97706" xmlns="http://www.w3.org/2000/svg">
  <path d="M18 3h-1V1H7v2H6C4.9 3 4 3.9 4 5v1c0 2.55 1.92 4.63 4.39 4.94.63 1.5 1.98 2.63 3.61 2.95V17H9v2H6v2h12v-2h-3v-2h-3v-3.11c1.63-.32 2.98-1.45 3.61-2.95C18.08 10.63 20 8.55 20 6V5c0-1.1-.9-2-2-2zM6 6V5h1v3.82C6.4 8.4 6 7.74 6 6zm12 0c0 1.74-.4 2.4-1 2.82V5h1v1z"/>
</svg>`;

function esc(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ---------------------------------------------------------------------
// Per-student data prep
// ---------------------------------------------------------------------
function prepStudent(student, certsByStudent) {
  const certs = certsByStudent[student._id] || [];
  const approved = certs.filter((c) => c.status === 'approved');
  const computedTotal = calcCappedPoints(approved, [], student.isLateralEntry);
  const threshold = passThreshold(student.isLateralEntry);
  const isPassing = computedTotal >= threshold;
  // Every student always has at least one "sub-row": either their activity
  // list, or a single "no approved activities" placeholder row. This list
  // is what actually gets paginated — never the block as a whole.
  const subRows =
    approved.length > 0
      ? approved.map((cert, ci) => ({ type: 'cert', cert, ci }))
      : [{ type: 'empty' }];

  return { student, approved, computedTotal, isPassing, subRows };
}

// ---------------------------------------------------------------------
// Row HTML builders (each function renders exactly one <tr>)
// ---------------------------------------------------------------------
function profileRowHtml({ student, computedTotal, isPassing, slIndex, rowSpan, continuation }) {
  const certCount = student.__certCount ?? 0;
  return `
    <tr class="student-profile-row${continuation ? ' continuation' : ''}">
      <td rowspan="${rowSpan}" class="sl-cell${continuation ? ' muted' : ''}">${slIndex}</td>
      <td class="student-name-meta">
        <div class="name-text">${esc(student.name) || '—'}${
          continuation ? '<span class="continued-tag">(continued)</span>' : ''
        }</div>
        ${
          continuation
            ? ''
            : `<div class="reg-meta-row">
                <span class="reg-text">Reg No: <b>${esc(student.registerNumber) || '—'}</b></span>
                ${student.isLateralEntry ? '<span class="lat-label">Lateral Entry</span>' : ''}
                <span class="cert-count-badge">${certCount} activit${certCount !== 1 ? 'ies' : 'y'}</span>
              </div>`
        }
      </td>
      <td class="points-cell pt-blank"></td>
      ${
        continuation
          ? `<td rowspan="${rowSpan}" colspan="2" class="continuation-note-cell">Continued from<br/>previous page</td>`
          : `<td rowspan="${rowSpan}" class="total-score-cell">
              <div class="total-score-num">${computedTotal}</div>
              <div class="total-score-label">pts</div>
            </td>
            <td rowspan="${rowSpan}" class="status-trophy-cell">
              ${
                isPassing
                  ? `<div class="trophy-wrapper">${TROPHY_SVG}<div class="pass-label">PASS</div></div>`
                  : '<div class="fail-wrapper"><div class="fail-label">PENDING</div></div>'
              }
            </td>`
      }
    </tr>`;
}

function subRowHtml(subRow, altShade) {
  const altClass = altShade ? ' alt' : '';
  if (subRow.type === 'empty') {
    return `
      <tr class="cert-item-row${altClass}">
        <td class="cert-name-cell empty-certs-text">No approved activities logged</td>
        <td class="points-cell">—</td>
      </tr>`;
  }
  const { cert, ci } = subRow;
  return `
    <tr class="cert-item-row${altClass}">
      <td class="cert-name-cell">
        <span class="cert-index">${ci + 1}.</span>
        ${esc(cert.eventName || cert.subcategory || '—')}
      </td>
      <td class="points-cell cert-pts">${cert.pointsAwarded ?? 0}</td>
    </tr>`;
}

function spacerRowHtml() {
  return `<tr class="spacer-row"><td colspan="5"></td></tr>`;
}

function tableHeadHtml() {
  return `
    <thead><tr>
      <th style="width:42px;">SI:NO</th>
      <th style="text-align:left;">NAME &amp; ACTIVITY SPECIFICATIONS</th>
      <th style="width:66px;">POINTS</th>
      <th style="width:76px;">TOTAL</th>
      <th style="width:70px;">STATUS</th>
    </tr></thead>`;
}

function headerBlockHtml(logoUrl, deptName) {
  return `
    <div class="header">
      <div class="header-logo-cell"><img src="${logoUrl}" /></div>
      <div class="header-text">
        <div class="dept-name">${esc(deptName)}</div>
        <div class="inst-name">MAHARAJA&#39;S TECHNOLOGICAL INSTITUTE (MTI)</div>
        <div class="inst-sub">Chembukkavu, Thrissur, Kerala – 680020</div>
        <div class="inst-sub">Affiliated to SBTE Kerala &nbsp;|&nbsp; AICTE Approved &nbsp;|&nbsp; Estd. 1946</div>
        <div class="inst-sub">Phone: 0487-2333290 &nbsp;|&nbsp; E-Mail: mtithrsr@mtithrissur.ac.in</div>
      </div>
      <div class="header-spacer-cell"></div>
    </div>`;
}

function titleBandHtml(batchLabel) {
  return `<div class="title-band">STUDENT ACTIVITY POINTS REPORT${batchLabel}</div>`;
}

function footerRowHtml(today, totalRecords) {
  return `
    <hr class="divider"/>
    <div class="footer-row">
      <div class="report-meta-footer">
        Generated on <b>${today}</b> &nbsp;|&nbsp; Total Records: <b>${totalRecords}</b>
      </div>
      <div class="report-meta-footer">
        MTI Student Activity Points System
      </div>
    </div>`;
}

async function waitForImages(root) {
  const imgs = Array.from(root.querySelectorAll('img'));
  await Promise.all(
    imgs.map(
      (img) =>
        new Promise((resolve) => {
          if (img.complete) return resolve();
          img.onload = () => resolve();
          img.onerror = () => resolve();
        })
    )
  );
}

function makeHiddenRoot() {
  const root = document.createElement('div');
  root.style.position = 'fixed';
  root.style.left = '-99999px';
  root.style.top = '0';
  root.style.zIndex = '-1';
  document.body.appendChild(root);
  return root;
}

/**
 * Renders a single department+batch "section" (header, title band, ledger
 * table, footer, with its own row-level pagination) into an existing jsPDF
 * document. Used both for a plain single-scope export and, repeatedly, for
 * a multi-section export that stacks one section per department/batch.
 *
 * `isVeryFirstPage` controls whether this section's first page reuses the
 * blank page jsPDF starts with (true) or starts a fresh page (false) — every
 * section after the first one in a multi-section document always starts on
 * a new page, never sharing a page with the previous section's footer.
 */
async function renderSectionIntoDoc(doc, { students, certsByStudent, branchName, batchName, logoUrl, isVeryFirstPage }) {
  const deptName = branchName ? `DEPARTMENT OF ${branchName.toUpperCase()}` : 'DEPARTMENT';
  const batchLabel = batchName ? ` — BATCH ${batchName}` : '';
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  const styleTag = `<style>${REPORT_CSS}</style>`;

  const prepared = students.map((s, i) => {
    const p = prepStudent(s, certsByStudent);
    p.slIndex = i + 1;
    p.student = { ...p.student, __certCount: p.approved.length };
    return p;
  });

  // --- Measure phase: render every row once (flat, rowspan-free) off-screen
  // to get its real rendered height, including any text-wrap effects on
  // long activity names. ---
  const measureRoot = makeHiddenRoot();
  const measureRowsHtml = [];
  prepared.forEach((p, pi) => {
    measureRowsHtml.push(
      `<tr data-key="profile-${pi}" class="student-profile-row"><td class="sl-cell">${p.slIndex}</td><td class="student-name-meta"><div class="name-text">${esc(
        p.student.name
      )}</div><div class="reg-meta-row"><span class="reg-text">Reg No: <b>${esc(
        p.student.registerNumber
      )}</b></span><span class="cert-count-badge">${p.approved.length} activities</span></div></td><td class="points-cell pt-blank"></td><td class="total-score-cell"><div class="total-score-num">${
        p.computedTotal
      }</div><div class="total-score-label">pts</div></td><td class="status-trophy-cell"></td></tr>`
    );
    p.subRows.forEach((sr, si) => {
      // Inject the data-key into the row's own <tr> tag instead of wrapping
      // it in a second one — subRowHtml()'s output starts with whitespace,
      // so a regex anchored at the very start of the string never matches,
      // silently leaving the original <tr> in place and nesting a second
      // <tr> inside it. Browsers can't nest <tr> inside <tr>: the parser
      // auto-closes the outer (data-key-bearing, cell-less) row as soon as
      // it hits the inner one, so every activity row ends up split into an
      // empty 0px-tall row that keeps the data-key and a separate content
      // row that loses it — meaning every measured sub-row height comes
      // back as ~0, the packing algorithm thinks 50+ activities take no
      // space, and everything gets crammed onto page 1 where it silently
      // overflows the printable page when rasterized.
      const rowHtml = subRowHtml(sr, false).trim();
      measureRowsHtml.push(rowHtml.replace(/^<tr/, `<tr data-key="sub-${pi}-${si}"`));
    });
  });
  measureRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc"><div class="ledger-wrap"><table class="ledger-table">${tableHeadHtml()}<tbody>${measureRowsHtml.join(
    ''
  )}</tbody></table></div></div>`;
  await waitForImages(measureRoot);

  const rowHeights = {};
  measureRoot.querySelectorAll('tr[data-key]').forEach((tr) => {
    rowHeights[tr.getAttribute('data-key')] = tr.offsetHeight;
  });
  const headerEl = measureRoot.querySelector('.header') || (() => {
    // header isn't in the measure DOM above; measure it separately below
    return null;
  })();
  document.body.removeChild(measureRoot);

  // Measure header/title-band height and thead height separately.
  const measureRoot2 = makeHiddenRoot();
  measureRoot2.innerHTML = `${styleTag}<div class="mti-pdf-doc">
    ${headerBlockHtml(logoUrl, deptName)}
    ${titleBandHtml(batchLabel)}
    <div class="ledger-wrap"><table class="ledger-table">${tableHeadHtml()}<tbody></tbody></table></div>
  </div>`;
  await waitForImages(measureRoot2);
  const hEl = measureRoot2.querySelector('.header');
  const tEl = measureRoot2.querySelector('.title-band');
  const theadEl = measureRoot2.querySelector('thead');
  const headerHeight = hEl.offsetHeight + tEl.offsetHeight;
  const theadHeight = theadEl.offsetHeight;
  const spacerHeight = 14; // fixed, from CSS
  document.body.removeChild(measureRoot2);

  // --- Packing phase: walk every student's sub-rows and assign them to
  // pages, splitting a student's activity list across a page boundary
  // (rather than ever discarding rows) when it doesn't fit on one page. ---
  const pages = []; // { includeHeader, chunks: [...] }
  let cur = null;
  let used = 0;

  function startPage(includeHeader) {
    cur = { includeHeader, chunks: [] };
    pages.push(cur);
    used = (includeHeader ? headerHeight : 0) + theadHeight;
  }
  startPage(true);

  prepared.forEach((p, pi) => {
    let si = 0;
    let isFirstChunk = true;
    while (si < p.subRows.length) {
      const headerRowH = rowHeights[`profile-${pi}`];
      const firstSubH = rowHeights[`sub-${pi}-${si}`];
      // Need room for this chunk's own header row + at least one sub-row;
      // otherwise start a fresh page before committing to this chunk.
      if (used + headerRowH + firstSubH > PAGE_CONTENT_MAX_PX) {
        startPage(false);
      }
      used += headerRowH;
      const chunkSubIndices = [];
      while (si < p.subRows.length && used + rowHeights[`sub-${pi}-${si}`] <= PAGE_CONTENT_MAX_PX) {
        used += rowHeights[`sub-${pi}-${si}`];
        chunkSubIndices.push(si);
        si++;
      }
      // Guarantee forward progress even in a pathological case where a
      // single row is taller than a whole page.
      if (chunkSubIndices.length === 0) {
        used += rowHeights[`sub-${pi}-${si}`];
        chunkSubIndices.push(si);
        si++;
      }
      const isLastChunk = si >= p.subRows.length;
      let includeSpacer = false;
      if (isLastChunk && used + spacerHeight <= PAGE_CONTENT_MAX_PX) {
        used += spacerHeight;
        includeSpacer = true;
      }
      cur.chunks.push({
        studentIndex: pi,
        isFirstChunk,
        isLastChunk,
        subIndices: chunkSubIndices,
        includeSpacer
      });
      isFirstChunk = false;
    }
  });

  // If the footer doesn't fit after the last page's content, give it its own page.
  const footerNeedsOwnPage = used + spacerHeight > PAGE_CONTENT_MAX_PX - 40;

  // --- Render phase: build the real HTML for each page from the chunk plan. ---
  for (let pg = 0; pg < pages.length; pg++) {
    const page = pages[pg];
    const isLastContentPage = pg === pages.length - 1;
    const showFooterHere = isLastContentPage && !footerNeedsOwnPage;

    let bodyHtml = '';
    page.chunks.forEach((chunk) => {
      const p = prepared[chunk.studentIndex];
      const rowSpan = 1 + chunk.subIndices.length;
      bodyHtml += profileRowHtml({
        student: p.student,
        computedTotal: p.computedTotal,
        isPassing: p.isPassing,
        slIndex: p.slIndex,
        rowSpan,
        continuation: !chunk.isFirstChunk
      });
      chunk.subIndices.forEach((si, k) => {
        bodyHtml += subRowHtml(p.subRows[si], k % 2 === 1);
      });
      if (chunk.includeSpacer) bodyHtml += spacerRowHtml();
    });

    const pageRoot = makeHiddenRoot();
    pageRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc">
      ${page.includeHeader ? headerBlockHtml(logoUrl, deptName) + titleBandHtml(batchLabel) : ''}
      <div class="ledger-wrap"><table class="ledger-table">${tableHeadHtml()}<tbody>${bodyHtml}</tbody></table></div>
      ${showFooterHere ? footerRowHtml(today, students.length) : ''}
    </div>`;

    await waitForImages(pageRoot);
    const target = pageRoot.querySelector('.mti-pdf-doc');
    const canvas = await html2canvas(target, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
      logging: false
    });
    document.body.removeChild(pageRoot);

    if (!(isVeryFirstPage && pg === 0)) doc.addPage();
    // JPEG at high quality instead of lossless PNG — a raster screenshot of
    // mostly text/tables compresses far better as JPEG (typically 5-10x
    // smaller) with no visible quality loss, and PDF file size scales
    // directly with page count here since every page is a full-page image.
    const imgData = canvas.toDataURL('image/jpeg', 0.92);
    const imgHmm = (canvas.height / canvas.width) * CONTENT_WIDTH_MM;
    doc.addImage(imgData, 'JPEG', MARGIN_X_MM, MARGIN_TOP_MM, CONTENT_WIDTH_MM, imgHmm);
  }

  if (footerNeedsOwnPage) {
    const pageRoot = makeHiddenRoot();
    pageRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc">${footerRowHtml(today, students.length)}</div>`;
    await waitForImages(pageRoot);
    const target = pageRoot.querySelector('.mti-pdf-doc');
    const canvas = await html2canvas(target, { scale: 2, backgroundColor: '#ffffff', useCORS: true, logging: false });
    document.body.removeChild(pageRoot);

    doc.addPage();
    const imgData = canvas.toDataURL('image/jpeg', 0.92);
    const imgHmm = (canvas.height / canvas.width) * CONTENT_WIDTH_MM;
    doc.addImage(imgData, 'JPEG', MARGIN_X_MM, MARGIN_TOP_MM, CONTENT_WIDTH_MM, imgHmm);
  }

}

/**
 * Generates and downloads the "Student Activity Points Report" PDF, visually
 * matching the report produced by the React Native tutor app.
 *
 * Accepts one or more `groups` — each `{ branchName, batchName, students }`
 * becomes its own self-contained section (own header, title band, ledger
 * table and footer, own row-level pagination), stacked one after another in
 * a single downloaded file. This is what makes a scoped tutor's single-page
 * report and a principal's "every department, every batch" report the same
 * code path: a tutor's export is just a one-group call.
 *
 * Pagination within each section is done row-by-row so a student's activity
 * list can never be truncated: if it doesn't fit on the current page it
 * simply continues, clearly marked, on the next one.
 */
export async function exportStudentsPdf({ groups, certsByStudent, logoUrl }) {
  if (!groups || groups.length === 0) {
    throw new Error('exportStudentsPdf: at least one group is required');
  }

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  for (let gi = 0; gi < groups.length; gi++) {
    const group = groups[gi];
    await renderSectionIntoDoc(doc, {
      students: group.students,
      certsByStudent,
      branchName: group.branchName,
      batchName: group.batchName,
      logoUrl,
      isVeryFirstPage: gi === 0
    });
  }

  // --- Page numbers (drawn directly by jsPDF), applied once across the
  // whole document so numbering is continuous across every section. ---
  const totalPages = doc.getNumberOfPages();
  const pageWmm = doc.internal.pageSize.getWidth();
  const pageHmm = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${i} of ${totalPages}`, pageWmm / 2, pageHmm - FOOTER_RESERVE_MM / 2, { align: 'center' });
  }

  // --- Filename ---
  const slug = (s) => (s || '').replace(/\s+/g, '_').toLowerCase();
  const fileDate = new Date().toLocaleDateString('en-IN').replace(/\//g, '-');
  let baseName;
  if (groups.length > 1) {
    // Multiple sections -> a broader export (all departments, or one
    // department's every batch, or one batch across every department).
    const branchNames = [...new Set(groups.map((g) => g.branchName).filter(Boolean))];
    const batchNames = [...new Set(groups.map((g) => g.batchName).filter(Boolean))];
    if (branchNames.length > 1 && batchNames.length > 1) {
      baseName = 'all_departments_all_batches';
    } else if (branchNames.length === 1) {
      baseName = `${slug(branchNames[0])}_all_batches`;
    } else if (batchNames.length === 1) {
      baseName = `all_departments_${slug(batchNames[0])}`;
    } else {
      baseName = 'activity_points_report';
    }
  } else {
    baseName = `${slug(groups[0].branchName) || 'dept'}_${slug(groups[0].batchName) || 'batch'}`;
  }
  doc.save(`${baseName}_${fileDate}.pdf`);
}

export { getBatchName, getBranchName };