/**
 * Tutor "Student Activity Points Report" PDF export.
 *
 * This mirrors the report generated by the React Native tutor app
 * (src/screens/TutorStudentsScreen.tsx -> buildPdfHtml + react-native-html-to-pdf)
 * as closely as possible: same header, same title band, same ledger table
 * layout/colors/typography, same PASS/PENDING trophy badges, same footer.
 *
 * Since the browser can't hand HTML off to a native WebKit PDF renderer the
 * way react-native-html-to-pdf does, we render the exact same markup/CSS to
 * an off-screen DOM node, rasterize each page with html2canvas, and paste
 * the images into a jsPDF document — paginating on student-group boundaries
 * so a student's row block is never sliced across a page break.
 */

import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { calcCappedPoints, passThreshold } from './calcPoints';

// ---------------------------------------------------------------------
// Layout constants
// ---------------------------------------------------------------------
// Rendered at this pixel width off-screen, then scaled down to fit the
// printable width of an A4 jsPDF page (210mm - margins).
const RENDER_WIDTH_PX = 900;
// Max height (px, at RENDER_WIDTH_PX) of content allowed on one page
// before we start a new page. Leaves room for the footer strip jsPDF
// draws on top afterwards.
const PAGE_CONTENT_MAX_PX = 1220;

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;
const MARGIN_X_MM = 10;
const MARGIN_TOP_MM = 10;
const FOOTER_RESERVE_MM = 12;

function getBatchName(b) {
  return typeof b === 'object' ? b?.name ?? '' : b ?? '';
}
function getBranchName(b) {
  return typeof b === 'object' ? b?.name ?? '' : b ?? '';
}

// ---------------------------------------------------------------------
// Shared CSS — a near-verbatim port of the RN report's stylesheet.
// ---------------------------------------------------------------------
const REPORT_CSS = `
.mti-pdf-doc, .mti-pdf-doc * { margin: 0; padding: 0; box-sizing: border-box; }
.mti-pdf-doc {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  color: #1e293b;
  background: #ffffff;
  font-size: 13px;
  width: ${RENDER_WIDTH_PX}px;
  padding: 18px 20px 10px 20px;
}
.mti-pdf-doc .header {
  display: table;
  width: 100%;
  padding-bottom: 14px;
  border-bottom: 3px solid #0f2864;
  margin-bottom: 12px;
}
.mti-pdf-doc .header-logo-cell { display: table-cell; vertical-align: middle; width: 92px; }
.mti-pdf-doc .header-logo-cell img { width: 72px; height: auto; display: block; }
.mti-pdf-doc .header-text { display: table-cell; vertical-align: middle; text-align: center; }
.mti-pdf-doc .dept-name { font-size: 17px; font-weight: 800; color: #0f2864; letter-spacing: 0.6px; margin-bottom: 3px; }
.mti-pdf-doc .inst-name { font-size: 14px; font-weight: 700; color: #1e293b; margin-bottom: 2px; }
.mti-pdf-doc .inst-sub { font-size: 10px; color: #64748b; margin-top: 1px; font-weight: 500; }
.mti-pdf-doc .title-band {
  background: linear-gradient(135deg, #0f2864 0%, #1e40af 100%);
  color: #ffffff;
  text-align: center;
  padding: 11px 14px;
  font-size: 14px;
  font-weight: 800;
  border-radius: 5px;
  margin: 14px 0 18px 0;
  letter-spacing: 1px;
}
.mti-pdf-doc .ledger-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
  background: #ffffff;
}
.mti-pdf-doc .ledger-table thead tr th {
  background-color: #0f2864;
  color: #ffffff;
  font-weight: 700;
  text-transform: uppercase;
  font-size: 10px;
  letter-spacing: 0.6px;
  padding: 10px 12px;
  border: 1px solid #0a1f54;
}
.mti-pdf-doc .student-profile-row td {
  border: 1.5px solid #94a3b8;
  background-color: #f0f4ff;
}
.mti-pdf-doc .sl-cell {
  text-align: center;
  font-weight: 800;
  font-size: 14px;
  color: #0f2864;
  background-color: #dce7ff !important;
  width: 42px;
  border-right: 2px solid #0f2864 !important;
}
.mti-pdf-doc .student-name-meta { padding: 10px 14px; }
.mti-pdf-doc .name-text {
  font-size: 14px;
  font-weight: 800;
  color: #0f2864;
  text-transform: uppercase;
  letter-spacing: 0.3px;
  margin-bottom: 4px;
}
.mti-pdf-doc .reg-meta-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.mti-pdf-doc .reg-text { font-size: 10px; color: #475569; }
.mti-pdf-doc .lat-label {
  background: #fef3c7;
  color: #92400e;
  font-size: 9px;
  font-weight: 700;
  padding: 1px 5px;
  border-radius: 3px;
  border: 1px solid #f59e0b;
}
.mti-pdf-doc .cert-count-badge {
  background: #e0f2fe;
  color: #0369a1;
  font-size: 9px;
  font-weight: 700;
  padding: 1px 6px;
  border-radius: 3px;
  border: 1px solid #7dd3fc;
}
.mti-pdf-doc .pt-blank { background-color: #f0f4ff !important; }
.mti-pdf-doc .cert-item-row td {
  border: 1px solid #e2e8f0;
  padding: 6px 12px;
  background: #ffffff;
}
.mti-pdf-doc .cert-name-cell { color: #334155; font-size: 11px; font-weight: 500; padding-left: 20px !important; }
.mti-pdf-doc .cert-index { color: #94a3b8; font-size: 10px; margin-right: 4px; font-weight: 600; }
.mti-pdf-doc .cert-pts { color: #0f2864; font-weight: 700 !important; text-align: center; }
.mti-pdf-doc .empty-certs-text { color: #94a3b8; font-style: italic; }
.mti-pdf-doc .points-cell { text-align: center; font-weight: 600; color: #475569; width: 66px; }
.mti-pdf-doc .total-score-cell {
  text-align: center;
  background: #0f2864 !important;
  border: 2px solid #0a1f54 !important;
  width: 76px;
  padding: 6px 4px;
}
.mti-pdf-doc .total-score-num { font-size: 24px; font-weight: 900; color: #ffffff; line-height: 1.1; }
.mti-pdf-doc .total-score-label { font-size: 9px; font-weight: 600; color: #93c5fd; text-transform: uppercase; letter-spacing: 0.5px; }
.mti-pdf-doc .status-trophy-cell {
  text-align: center;
  background: #ffffff !important;
  border: 1.5px solid #94a3b8 !important;
  width: 70px;
  padding: 4px;
}
.mti-pdf-doc .trophy-wrapper { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 2px; }
.mti-pdf-doc .trophy-wrapper svg { width: 24px; height: 24px; }
.mti-pdf-doc .pass-label { font-size: 9px; font-weight: 800; color: #15803d; letter-spacing: 0.5px; }
.mti-pdf-doc .fail-wrapper { display: flex; align-items: center; justify-content: center; height: 100%; }
.mti-pdf-doc .fail-label { font-size: 9px; font-weight: 700; color: #94a3b8; letter-spacing: 0.5px; }
.mti-pdf-doc .spacer-row td {
  height: 14px;
  background: transparent !important;
  border: none !important;
  padding: 0 !important;
}
.mti-pdf-doc .divider { border: none; border-top: 2px solid #e2e8f0; margin: 20px 0 8px 0; }
.mti-pdf-doc .report-meta-footer { font-size: 10px; color: #64748b; font-weight: 500; }
.mti-pdf-doc .footer-row { display: flex; justify-content: space-between; align-items: center; }
`;

// Inline trophy SVG (stand-in for the Material Icons "emoji_events" glyph
// used in the RN app — avoids depending on a webfont being loaded in time
// for html2canvas to rasterize it).
const TROPHY_SVG = `<svg viewBox="0 0 24 24" fill="#d97706" xmlns="http://www.w3.org/2000/svg">
  <path d="M18 3h-1V1H7v2H6C4.9 3 4 3.9 4 5v1c0 2.55 1.92 4.63 4.39 4.94.63 1.5 1.98 2.63 3.61 2.95V17H9v2H6v2h12v-2h-3v-2h-3v-3.11c1.63-.32 2.98-1.45 3.61-2.95C18.08 10.63 20 8.55 20 6V5c0-1.1-.9-2-2-2zM6 6V5h1v3.82C6.4 8.4 6 7.74 6 6zm12 0c0 1.74-.4 2.4-1 2.82V5h1v1z"/>
</svg>`;

function buildTbodyHtml(student, certsByStudent) {
  const certs = certsByStudent[student._id] || [];
  const approved = certs.filter((c) => c.status === 'approved');
  const computedTotal = calcCappedPoints(approved, [], student.isLateralEntry);
  const threshold = passThreshold(student.isLateralEntry);
  const isPassing = computedTotal >= threshold;
  const totalRowsCount = approved.length > 0 ? approved.length + 1 : 2;
  const certCount = approved.length;

  let rowGroupHtml = `
    <tr class="student-profile-row">
      <td rowspan="${totalRowsCount}" class="sl-cell">${student.__idx}</td>
      <td class="student-name-meta">
        <div class="name-text">${esc(student.name) || '—'}</div>
        <div class="reg-meta-row">
          <span class="reg-text">Reg No: <b>${esc(student.registerNumber) || '—'}</b></span>
          ${student.isLateralEntry ? '<span class="lat-label">Lateral Entry</span>' : ''}
          <span class="cert-count-badge">${certCount} activit${certCount !== 1 ? 'ies' : 'y'}</span>
        </div>
      </td>
      <td class="points-cell pt-blank"></td>
      <td rowspan="${totalRowsCount}" class="total-score-cell">
        <div class="total-score-num">${computedTotal}</div>
        <div class="total-score-label">pts</div>
      </td>
      <td rowspan="${totalRowsCount}" class="status-trophy-cell">
        ${
          isPassing
            ? `<div class="trophy-wrapper">${TROPHY_SVG}<div class="pass-label">PASS</div></div>`
            : '<div class="fail-wrapper"><div class="fail-label">PENDING</div></div>'
        }
      </td>
    </tr>
  `;

  if (approved.length === 0) {
    rowGroupHtml += `
      <tr class="cert-item-row">
        <td class="cert-name-cell empty-certs-text">No approved activities logged</td>
        <td class="points-cell">—</td>
      </tr>`;
  } else {
    approved.forEach((cert, ci) => {
      rowGroupHtml += `
        <tr class="cert-item-row">
          <td class="cert-name-cell">
            <span class="cert-index">${ci + 1}.</span>
            ${esc(cert.eventName || cert.subcategory || '—')}
          </td>
          <td class="points-cell cert-pts">${cert.pointsAwarded ?? 0}</td>
        </tr>`;
    });
  }

  rowGroupHtml += `
    <tr class="spacer-row">
      <td colspan="5"></td>
    </tr>`;

  return `<tbody class="student-ledger-group">${rowGroupHtml}</tbody>`;
}

function esc(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function tableHeadHtml() {
  return `
    <thead><tr>
      <th style="width:42px;">SI:NO</th>
      <th style="text-align:left;">NAME &amp; ACTIVITY SPECIFICATIONS</th>
      <th style="width:66px;">POINTS</th>
      <th style="width:76px;">TOTAL</th>
      <th style="width:70px;">STATUS</th>
    </tr></thead>`;
}

function headerBlockHtml(logoUrl, deptName) {
  return `
    <div class="header">
      <div class="header-logo-cell"><img src="${logoUrl}" /></div>
      <div class="header-text">
        <div class="dept-name">${esc(deptName)}</div>
        <div class="inst-name">MAHARAJA&#39;S TECHNOLOGICAL INSTITUTE (MTI)</div>
        <div class="inst-sub">Chembukkavu, Thrissur, Kerala – 680020</div>
        <div class="inst-sub">Affiliated to SBTE Kerala &nbsp;|&nbsp; AICTE Approved &nbsp;|&nbsp; Estd. 1946</div>
        <div class="inst-sub">Phone: 0487-2333290 &nbsp;|&nbsp; E-Mail: mtithrsr@mtithrissur.ac.in</div>
      </div>
    </div>`;
}

function titleBandHtml(batchLabel) {
  return `<div class="title-band">STUDENT ACTIVITY POINTS REPORT${batchLabel}</div>`;
}

function footerRowHtml(today, totalRecords) {
  return `
    <hr class="divider"/>
    <div class="footer-row">
      <div class="report-meta-footer">
        Generated on <b>${today}</b> &nbsp;|&nbsp; Total Records: <b>${totalRecords}</b>
      </div>
      <div class="report-meta-footer">
        MTI Student Activity Points System
      </div>
    </div>`;
}

async function waitForImages(root) {
  const imgs = Array.from(root.querySelectorAll('img'));
  await Promise.all(
    imgs.map(
      (img) =>
        new Promise((resolve) => {
          if (img.complete) return resolve();
          img.onload = () => resolve();
          img.onerror = () => resolve();
        })
    )
  );
}

/**
 * Generates and downloads the tutor "Student Activity Points Report" PDF,
 * visually matching the report produced by the React Native tutor app.
 */
export async function exportStudentsPdf({ students, certsByStudent, tutorBranch, tutorBatch, logoUrl }) {
  const deptName = tutorBranch ? `DEPARTMENT OF ${tutorBranch.toUpperCase()}` : 'DEPARTMENT';
  const batchLabel = tutorBatch ? ` — BATCH ${tutorBatch}` : '';
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  const numbered = students.map((s, i) => ({ ...s, __idx: i + 1 }));
  const tbodyHtmlList = numbered.map((s) => buildTbodyHtml(s, certsByStudent));

  // --- Measure phase: render everything off-screen once to get real heights ---
  const measureRoot = document.createElement('div');
  measureRoot.style.position = 'fixed';
  measureRoot.style.left = '-99999px';
  measureRoot.style.top = '0';
  measureRoot.style.zIndex = '-1';
  document.body.appendChild(measureRoot);

  const styleTag = `<style>${REPORT_CSS}</style>`;
  measureRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc">
    ${headerBlockHtml(logoUrl, deptName)}
    ${titleBandHtml(batchLabel)}
    <table class="ledger-table">${tableHeadHtml()}${tbodyHtmlList.join('')}</table>
  </div>`;

  await waitForImages(measureRoot);

  const docEl = measureRoot.querySelector('.mti-pdf-doc');
  const headerEl = docEl.querySelector('.header');
  const titleBandEl = docEl.querySelector('.title-band');
  const theadEl = docEl.querySelector('thead');
  const tbodyEls = Array.from(docEl.querySelectorAll('tbody.student-ledger-group'));

  const headerHeight = headerEl.offsetHeight + titleBandEl.offsetHeight;
  const theadHeight = theadEl.offsetHeight;
  const tbodyHeights = tbodyEls.map((el) => el.offsetHeight);

  document.body.removeChild(measureRoot);

  // --- Paginate on student-group boundaries ---
  const pages = [];
  let idx = 0;
  let firstPage = true;
  while (idx < tbodyHtmlList.length) {
    let used = (firstPage ? headerHeight : 0) + theadHeight;
    const indices = [];
    while (idx < tbodyHtmlList.length && (indices.length === 0 || used + tbodyHeights[idx] <= PAGE_CONTENT_MAX_PX)) {
      used += tbodyHeights[idx];
      indices.push(idx);
      idx++;
    }
    pages.push({ includeHeader: firstPage, indices });
    firstPage = false;
  }
  if (pages.length === 0) {
    pages.push({ includeHeader: true, indices: [] });
  }

  // If the footer doesn't fit after the last page's content, give it its own page.
  const lastPage = pages[pages.length - 1];
  const lastUsed =
    (lastPage.includeHeader ? headerHeight : 0) +
    theadHeight +
    lastPage.indices.reduce((s, i) => s + tbodyHeights[i], 0);
  const footerNeedsOwnPage = lastUsed > PAGE_CONTENT_MAX_PX - 60;

  // --- Render + capture each page ---
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const contentWmm = A4_WIDTH_MM - MARGIN_X_MM * 2;

  for (let p = 0; p < pages.length; p++) {
    const page = pages[p];
    const isLastContentPage = p === pages.length - 1;
    const showFooterHere = isLastContentPage && !footerNeedsOwnPage;

    const pageRoot = document.createElement('div');
    pageRoot.style.position = 'fixed';
    pageRoot.style.left = '-99999px';
    pageRoot.style.top = '0';
    pageRoot.style.zIndex = '-1';
    document.body.appendChild(pageRoot);

    const bodyHtml = page.indices.map((i) => tbodyHtmlList[i]).join('');
    pageRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc">
      ${page.includeHeader ? headerBlockHtml(logoUrl, deptName) + titleBandHtml(batchLabel) : ''}
      <table class="ledger-table">${tableHeadHtml()}${bodyHtml}</table>
      ${showFooterHere ? footerRowHtml(today, students.length) : ''}
    </div>`;

    await waitForImages(pageRoot);
    const target = pageRoot.querySelector('.mti-pdf-doc');
    const canvas = await html2canvas(target, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
      logging: false,
    });
    document.body.removeChild(pageRoot);

    if (p > 0) doc.addPage();
    const imgData = canvas.toDataURL('image/png');
    const imgHmm = (canvas.height / canvas.width) * contentWmm;
    doc.addImage(imgData, 'PNG', MARGIN_X_MM, MARGIN_TOP_MM, contentWmm, imgHmm);
  }

  if (footerNeedsOwnPage) {
    const pageRoot = document.createElement('div');
    pageRoot.style.position = 'fixed';
    pageRoot.style.left = '-99999px';
    pageRoot.style.top = '0';
    pageRoot.style.zIndex = '-1';
    document.body.appendChild(pageRoot);
    pageRoot.innerHTML = `${styleTag}<div class="mti-pdf-doc">${footerRowHtml(today, students.length)}</div>`;
    await waitForImages(pageRoot);
    const target = pageRoot.querySelector('.mti-pdf-doc');
    const canvas = await html2canvas(target, { scale: 2, backgroundColor: '#ffffff', useCORS: true, logging: false });
    document.body.removeChild(pageRoot);

    doc.addPage();
    const imgData = canvas.toDataURL('image/png');
    const imgHmm = (canvas.height / canvas.width) * contentWmm;
    doc.addImage(imgData, 'PNG', MARGIN_X_MM, MARGIN_TOP_MM, contentWmm, imgHmm);
  }

  // --- Page numbers (drawn directly by jsPDF, same as before) ---
  const totalPages = doc.getNumberOfPages();
  const pageWmm = doc.internal.pageSize.getWidth();
  const pageHmm = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${i} of ${totalPages}`, pageWmm / 2, pageHmm - FOOTER_RESERVE_MM / 2, { align: 'center' });
  }

  const branchSlug = (tutorBranch || 'dept').replace(/\s+/g, '_').toLowerCase();
  const batchSlug = (tutorBatch || 'batch').replace(/\s+/g, '_').toLowerCase();
  const fileDate = new Date().toLocaleDateString('en-IN').replace(/\//g, '-');
  doc.save(`${branchSlug}_${batchSlug}_${fileDate}.pdf`);
}

export { getBatchName, getBranchName };
